fix: move output below input to be less confusing
ipfs/ipfs-webui pull request #1806
Opened 2021-06-18 15:13 UTC by olizilla

...in some scenarios. it's a stacked graph, so the total height is in+out, when out is tiny and in is large it is not obvious that out is a tiny sliver stacked on top.

<img width="1244" alt="Screenshot 2021-06-18 at 15 05 06" src="https://user-images.githubusercontent.com/58871/122582061-9e31f500-d04f-11eb-8915-992ce60e5eb4.png">

fixes #1797
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

2021-06-18 15:16 UTC, olizilla commented
Up next, actually seperate out in vs out.

2021-06-18 15:17 UTC, olizilla commented
it's also confusing that the 2 guages do not use the same range, but are ranged per direction... it makes visual comparison of the 2 gauages meaningless. They need to share the same max value.

2021-06-18 15:20 UTC, olizilla commented
last commit fixes it so out going bandwidth is negative so you can visually compare in vs out

<img width="1243" alt="Screenshot 2021-06-18 at 16 16 42" src="https://user-images.githubusercontent.com/58871/122583363-0b925580-d051-11eb-9020-11182ac0c4c7.png">

2021-06-21 15:49 UTC, lidel requested changes
Thank you @olizilla, this approach looks like a good way to fix confusion causing issues like #1797 

Two asks:
1. Can you rebase this on top of `main` branch, so this PR is on top of v0.12.3  (right now this PR is based on v0.12.0 – perhaps you have old `master` locally? It got renamed a while ago). 
   - This is important because we changed units in https://github.com/ipfs/ipfs-webui/pull/1791 (v2.12.3) and we talked about reverting units for bandwidth during friday's triage.
2. (cosmetic) Negative numbers in [point popup and left axis look bit weird](https://user-images.githubusercontent.com/157609/122790144-4f3ac880-d2b8-11eb-9823-994ca6d8ca2d.png) but if its not possible to fix it without changing the lib responsible for plotting graph,

2021-07-05 11:36 UTC, lidel commented
Rebased and reverted BW unit change from https://github.com/ipfs/ipfs-webui/pull/1791 – WebUI should now show the same numeric values as `ipfs stats bw`.
I also tweaked units, values in tooltip and legend to be unified as well:

> ![2021-07-05--13-34-08](https://user-images.githubusercontent.com/157609/124465736-0abe2b00-dd96-11eb-9fe0-80d4a8a96018.png)

2021-07-05 11:43 UTC, lidel commented
Just to be sure, units+values match confirmed with quick eyeballing:

> ![2021-07-05--13-41-10](https://user-images.githubusercontent.com/157609/124466332-da2ac100-dd96-11eb-967f-852e2025810e.png)

2021-07-05 11:45 UTC, lidel approved these changes

2021-07-05 11:47 UTC, merged