feat: export DAG CAR via the context menu
ipfs/ipfs-webui pull request #1837
Opened 2021-08-18 09:57 UTC by hacdias

Partially addresses #1798.

![Screen Shot 2021-08-18 at 11 56 20](https://user-images.githubusercontent.com/5447088/129878608-0dabc765-056c-4b87-ad97-ef95aca54125.png).

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

2021-08-18 13:15 UTC, rafaelramalho19 approved these changes

2021-08-18 21:21 UTC, lidel reviewed
@rvagg @olizilla @mikeal   @alanshaw 
Would appreciate some opinionated  bikeshed around labels related to DAG export/import in UI (webui/desktop).

Does the above screenshot look sensible?

Mainly, I want this to be consistent with messaging we have in dev docs in other places (are we using "DAG export" or "CAR download" etc)?

2021-08-19 00:23 UTC, rvagg commented
I think this is probably OK, we've put IPFS' "export" inside the "dag" subsection and it's technically correct that it's exporting an entire DAG starting from a root.

We have other place that are front-loading "CAR", like web3.storage which has a `putCar()` API (though not in docs yet I think), but I'm not sure that's the ideal approach as it would be good to have some wriggle room around transports for moving DAGs around and not box ourselves too tightly into a form. Even the `putCar()` API in web3.storage just means "give me an object that conforms to the `CarReader` API, which it then just uses as a simple root provider blockstore (I faked this for percid.va.gg so I could use that API but not deal with CARs).

2021-09-02 00:07 UTC, lidel requested changes
LGTM but let's park this until we have a PR with import  as noted in https://github.com/ipfs/ipfs-webui/issues/1798#issuecomment-910930951

2022-06-06 18:33 UTC, lidel requested changes

2022-06-06 18:33 UTC, lidel commented on src/lib/files.js
> +    url: `${apiUrl}/api/v0/dag/export?arg=${cid}`,
@hacdias go-ipfs 0.13 will allow for fetching CAR from gateway, mind refactoring this, so we use below?

```suggestion
    url: `${gatewayUrl}/ipfs/${cid}?format=car&filename=${filename || cid}.car`,
```

(would be cool if we could preserve filename, if not, cid is fine too)

2022-06-06 18:33 UTC, lidel commented on public/locales/en/app.json
> +    "exportDag": "Export DAG"
All docs in ecosystem refer to CARs, maybe it is better to rename this to:
```suggestion
    "exportDag": "Download as CAR"
```

2022-06-09 12:16 UTC, hacdias commented
@lidel I rebased and made the necessary updates to use the new gateway URLs and the nomenclature. I will now update #1838 such that it matches and is rebased.

Besides, I added some of the mechanics we use in #1894 such that we don't store the whole file in memory downloading it. We create an artificial `a` block and click on it.

On a different note, the gateway download doesn't follow the `filename` query parameter. I opened an issue in https://github.com/ipfs/go-ipfs/issues/9027 about it.

2022-06-09 20:01 UTC, lidel approved these changes
LGTM, this is unblocked because  go-ipfs 0.13 supports `?format=car` ([release notes](https://github.com/ipfs/go-ipfs/releases/tag/v0.13.0)) and we now have PR with gateway specs at https://github.com/ipfs/specs/pull/283

Needs small unicode fix below, but I'll apply it shortly. 

Unsure why CI deps install fail, probably the usual NPM rot. 
Will regenerate package-lock and see if that helps.

2022-06-09 22:51 UTC, merged