chore: pull transifex translations automatically
ipfs/ipfs-webui pull request #1956
Opened 2022-06-28 18:52 UTC by SgtPooki

This github action, .github/workflows/tx-pull.yml, will

  1. automatically pull translations
  2. automatically create a commit to a `tx-pull-<github_sha>` branch
  3. automatically open a PR from that branch to the main branch

2022-06-28 20:04 UTC, lidel requested changes
lgtm, but running it on every push is too much, suggestions inline

2022-06-28 20:04 UTC, lidel commented on .github/workflows/tx-pull.yml
> +  pull-request:
Do we need two jobs here? iiuc everything could be done in one, removing need for passing things in cache

2022-06-29 20:21 UTC, SgtPooki commented on .github/workflows/tx-pull.yml
> +    - main
The only problem with this, is that I don't think the github action I'm using for creating PRs supports updating PRs. Do you know of a github action that would accomplish that?

2022-06-29 21:10 UTC, lidel commented on .github/workflows/tx-pull.yml
> +    - main
I think `repo-sync/pull-request` does force-push if branch already exists?

We use it [here](https://github.com/ipfs/ipfs-docs/blob/main/.github/workflows/update-on-new-ipfs-tag.yml#L23), and it seems to force-push [here](https://github.com/ipfs/ipfs-docs/pull/1174), so maybe it already works but is not documented?

I agree there is no point in spending time on this right now – let's just leave it as-is and see how it behaves in real life, we can improve this workflow in future PRs.

2022-06-29 21:12 UTC, lidel commented on .github/workflows/tx-pull.yml
> +  pull-request:
ack, let's leave it as-is, we can simplify in future PR.

2022-06-29 21:12 UTC, lidel approved these changes

2022-06-29 21:13 UTC, merged