2004 add pinning service providers to default list estuary
ipfs/ipfs-webui pull request #2026
Opened 2022-09-14 18:30 UTC by SgtPooki

- feat: add Web3.Storage default pinning provider
- feat: add Estuary default pinning provider

2022-09-14 18:46 UTC, SgtPooki commented
Links to compliance reports are all working as well
![image](https://user-images.githubusercontent.com/1173416/190237531-1e6a8b00-a707-41d9-8b87-c706eb6d79eb.png)

2022-09-14 18:54 UTC, lidel requested changes
lgtm, but this will ship with IPFS Desktop and Kubo, it may introduce issue triage load coming from less technical users.

Before we merge this, would like to get official :+1:  from projects themselves.
Pinging:

- web3.storage @alanshaw @vasco-santos or  @olizilla 
- estuary @jimmylee  @whyrusleeping

2022-09-14 18:54 UTC, lidel commented on src/constants/pinning.js
> +    icon: 'https://bafybeiaqsdwuwemchbofzok4cq7cuvotfs6bgickxdqr6f7hdt7a64cwwa.ipfs.w3s.link/Web3.Storage-logo.svg',
```suggestion
    icon: 'https://dweb.link/ipfs/bafybeiaqsdwuwemchbofzok4cq7cuvotfs6bgickxdqr6f7hdt7a64cwwa/Web3.Storage-logo.svg',
```

2022-09-14 18:58 UTC, jimmylee commented
LGTM

2022-09-15 07:51 UTC, vasco-santos approved these changes
LGTM 👍🏼

2022-09-15 17:43 UTC, lidel approved these changes
We got :+1:  from both teams :)

2022-09-15 19:34 UTC, merged