Feat: Bulk CIDs Import
ipfs/ipfs-webui pull request #2307
Opened 2024-11-30 01:53 UTC by MattWong-ca

TBD

2024-12-09 17:19 UTC, MattWong-ca commented
Hey @SgtPooki, I've updated the PR description and added a video, this is good to go for review!

2024-12-13 16:34 UTC, SgtPooki requested changes
this is great, thanks so much! Only change I can see that is needed is the removal of prop-types, and having the new `BulkImportModal` be a functional typescript component.

Also, we should use kebab-case-filenames instead of CamelCase. This repo hasn't been fully updated, but that's where we're going

2024-12-13 16:34 UTC, SgtPooki commented on src/files/modals/bulk-import-modal/BulkImportModal.js
> +export default withTranslation('files')(BulkImportModal)
use `useTranslation('files')` once this is converted to a functional component instead of `withTranslation`

2024-12-13 16:34 UTC, SgtPooki commented on src/files/modals/bulk-import-modal/BulkImportModal.js
> +class BulkImportModal extends React.Component {
we should convert this to a functional component.

2024-12-13 16:34 UTC, SgtPooki commented on src/files/modals/bulk-import-modal/BulkImportModal.js
> +  }
we should remove prop-types. Eventually, we're moving this whole repo to typescript and will get type safety during transpilation.

2024-12-13 16:34 UTC, SgtPooki commented on src/files/modals/bulk-import-modal/BulkImportModal.js
> +import React from 'react'
We should use typescript for new files

2024-12-13 22:37 UTC, MattWong-ca commented
> this is great, thanks so much! Only change I can see that is needed is the removal of prop-types, and having the new `BulkImportModal` be a functional typescript component.
> 
> Also, we should use kebab-case-filenames instead of CamelCase. This repo hasn't been fully updated, but that's where we're going

Thanks @SgtPooki, just finished addressing all the comments!

2025-01-18 09:13 UTC, MattWong-ca commented
Hey @SgtPooki, wanted to bump this!

2025-01-29 21:48 UTC, SgtPooki reviewed
code looks okay, let me check locally

2025-01-29 21:53 UTC, SgtPooki commented
this worked great... let me merge main and give you an approval

2025-01-29 21:53 UTC, SgtPooki approved these changes

2025-02-27 16:22 UTC, merged